@DockerAspNetApps_SampleApi_HostAddress = http://localhost:5180

GET {{DockerAspNetApps_SampleApi_HostAddress}}/architecture/
Accept: application/json

###

GET {{DockerAspNetApps_SampleApi_HostAddress}}/hello/
Accept: application/json
